apiVersion: apps/v1
kind: Deployment
metadata:
  name: overpass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overpass
  template:
    metadata:
      labels:
        app: overpass
    spec:
      containers:
        - name: overpass
          image: wiktorn/overpass-api
          ports:
            - containerPort: 80
              hostPort: 8002
          env:
            - name: OVERPASS_MODE
              value: clone
            - name: OVERPASS_META
              value: "yes"
            - name: OVERPASS_RULES_LOAD
              value: "80"
            - name: OVERPASS_USE_AREAS
              value: "true"
            - name: OVERPASS_FASTCGI_PROCESSES
              value: "12"
            - name: OVERPASS_RATE_LIMIT
              value: "10"
            - name: OVERPASS_MAX_TIMEOUT
              value: "60000"
            - name: OVERPASS_TIME
              value: "30000"
            - name: OVERPASS_SPACE
              value: "34359738368"
          resources:
            requests:
              memory: 48Gi
            limits:
              memory: 48Gi
          volumeMounts:
            - name: overpass-db
              mountPath: /db
            - name: overpass-shm
              mountPath: /dev/shm
      volumes:
        - name: overpass-db
          hostPath:
            path: /everything/src/github.com/yuiseki/osm-planet-in-da-house/data/overpass/db_planet
            type: Directory
        - name: overpass-shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: overpass
spec:
  selector:
    app: overpass
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
